// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgndwnexswqtjjigojqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnbmR3bmV4c3dxdGpqaWdvanFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzMyMTksImV4cCI6MjA3MDQwOTIxOX0.WquvqkkK8nFUnYyw7YHFmYhA0gmYqO7ExvR9Ky4AV0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});